models/Pengguna.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-01 22:06:08
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-29 16:34:39
*/

namespace app\models;

use Yii;

/**
 * This is the model class for table "pengguna".
 *
 * @property int $id
 * @property string $hak_akses [ admin,rs,unit ]
 * @property string $username
 * @property string $password
 * @property string $nama_rs_puskesmas
 * @property string $kontak
 * @property string $email
 * @property string $alamat
 */
class Pengguna extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pengguna';
    }

    // public function beforeSave($insert) {
    //     if(isset($this->password)) 
    //         $this->password = Security::generatePasswordHash($this->password);
    //     return parent::beforeSave($insert);
    // }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password'], 'required', 'message' => '{attribute} tidak boleh kosong.'],
            [['hak_akses', 'nama_rs_puskesmas', 'kontak', 'alamat'], 'required', 'message' => '{attribute} tidak boleh kosong.'],
            [['email'], 'safe'],

            [['username'], 'unique', 'on'=>'update', 'when' => function($model){
                    return static::getOldUsername(14) !== $model->username;
                }
            ],
            

            ['username', 'unique', 'on' => 'tambah'],

            // [['username'], 'unique','on' => 'tambah'],

            [['alamat'], 'string'],
            [['hak_akses'], 'string', 'max' => 15],
            [['username', 'password'], 'string', 'max' => 250],
            [['nama_rs_puskesmas'], 'string', 'max' => 250],
            [['kontak'], 'string', 'max' => 15],
            [['email'], 'string', 'max' => 100],
        ];
    }

    public static function getOldUsername($id)
    {
        return static::findIdentity($id)->username;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'hak_akses' => 'Hak Akses',
            'username' => 'Username',
            'password' => 'Password',
            'nama_rs_puskesmas' => 'Nama Rumah Sakit / Puskesmas',
            'kontak' => 'Kontak',
            'email' => 'Email',
            'alamat' => 'Alamat',
        ];
    }

}

controllers/PenggunaController.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-01 22:07:36
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-29 16:39:01
*/

namespace app\controllers;

use Yii;
use app\models\Pengguna;
use app\models\PenggunaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\form\ActiveForm;


use yii\filters\AccessControl;
use app\components\AccessRule;
use app\models\User;

/**
 * PenggunaController implements the CRUD actions for Pengguna model.
 */
class PenggunaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // We will override the default rule config with the new AccessRule class
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'only' => [
                    //super_admin
                    'index', 'tambah', 'detail', 'delete'
                ],
                'rules' => [
                    [
                        'actions' => ['index', 'tambah', 'detail', 'delete'],
                        'allow' => true,
                        'roles' => [
                            User::ROLE_SUPERADMIN,
                        ],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pengguna models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PenggunaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTesBulk()
    {
        $searchModel = new PenggunaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;

        return $this->render('tes-bulk', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pengguna model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pengguna model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionValidasi()
    {
        $model = new Pengguna();
        // $model->scenario = 'update';

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()))
        {
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
            // return 'kakek';

            // return $model->scenario;
        }
    }

    public function actionTambah()
    {
        $model = new Pengguna();
        $model->scenario = 'tambah';

        // print_r($model->scenario);exit;

        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        if ($model->load(Yii::$app->request->post())) {
            // $model->password = password_hash($model->password, PASSWORD_DEFAULT);
            if($model->save()) {
                Yii::$app->getSession()->setFlash('success', 'Pengguna Berhasil ditambah.');
                return $this->redirect('index');
            }
        }
        $model->hak_akses = 'user';
        return $this->render('tambah', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pengguna model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        // $model->scenario = 'update';

        if ($model->load(Yii::$app->request->post())) {
            // $model->password = password_hash($model->password, PASSWORD_DEFAULT);
            if($model->save()) {
                Yii::$app->getSession()->setFlash('success', 'Pengguna Berhasil diubah.');
                return $this->redirect('index');
                // return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pengguna model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pengguna model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pengguna the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pengguna::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    // =============================================UNTUK MODAL====================================================
    public function actionDetail()
    {
        $model = $this->findModel($_GET['id']);

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            $model->refresh();
        } else {
            return $this->renderAjax('view',[
                'model' => $model
            ]);
        }
    }
}

views/pengguna/_form.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-01 22:07:36
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-28 11:27:25
*/

use yii\helpers\Html;
use yii\helpers\Url;
// use yii\widgets\ActiveForm;
use kartik\form\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Pengguna */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pengguna-form">

<div class="panel panel-primary">
  <div class="panel-heading">Data Pengguna</div>
  <div class="panel-body">
    <?php 
        $form = ActiveForm::begin([
            // 'id' => 'login-form-horizontal', 
            'id' => $model->formName(), 
            'type' => ActiveForm::TYPE_HORIZONTAL,
            'formConfig' => ['labelSpan' => 3, 'deviceSize' => ActiveForm::SIZE_SMALL],
            'enableAjaxValidation' => true,
            'validationUrl' => Url::toRoute('pengguna/validasi')
        ]); 

        $hakAkses = [
            // 'admin' => 'ADMIN',
            'user' => 'USER'
        ];
    ?>

    <?php 
        if($model->hak_akses=='super_admin' || $model->hak_akses=='admin'){
            Html::activeHiddenInput($model, 'hak_akses', ['value' => $model->hak_akses]);
        }else{
            echo $form->field($model, 'hak_akses')->radioButtonGroup($hakAkses, [
                'class' => 'btn-group-md',
                'itemOptions' => ['labelOptions' => ['class' => 'btn btn-default']],
            ]);
        }
    ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nama_rs_puskesmas')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'kontak')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'alamat')->textarea(['rows' => 6]) ?>

  
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary']) ?>
            <?php // Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
  </div>
</div>

</div>

views/pengguna/_search.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-01 22:07:36
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-12 21:30:12
*/

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PenggunaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pengguna-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'hak_akses') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'nama_rs_puskesmas') ?>

    <?php // echo $form->field($model, 'kontak') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'alamat') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pengguna/index.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-01 22:07:36
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-15 22:40:14
*/

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\icons\Icon;

use app\assets\ModalAsset;


ModalAsset::register($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\PenggunaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Pengguna';
$this->params['breadcrumbs'][] = $this->title;
?>

<style>
    .modal-dialog {
        top: 7%;
    }
</style>

<div class="pengguna-index">

    <p>
        <?= Html::a(Icon::show('user-plus'). ' Tambah Pengguna', ['tambah'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        // 'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
        'rowOptions' => function($model) {
            if ($model->id==2) return ['class' => 'info'];
            if ($model->id==1) return ['class' => 'info'];
        },
        'pager' => [
            'firstPageLabel' => 'Pertama',
            'lastPageLabel'  => 'Terakhir'
        ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            'hak_akses',
            
            'nama_rs_puskesmas',
            'username',
            // 'kontak',
            // 'email:email',
            // 'alamat:ntext',

            [
                'class'    => 'yii\grid\ActionColumn',
                'template' => '{leadView}<br/>{leadUpdate}<br/>{leadDelete}',
                'visibleButtons'=>[
                    'leadDelete'=> function($model){
                          return $model->id!=1 && $model->id!=2;
                     },
                ],
                'buttons'  => [
                    // 'leadView'   => function ($url, $model) {
                    //     $url = Url::to(['pengguna/view', 'id' => $model->id]);
                    //     return Html::a('Lihat', $url, ['title' => 'view', 'class' => 'btn btn-info btn-xs', 'style' => 'width:100%']);
                    // },
                    'leadView'   => function ($url, $model) {
                        return Html::button(
                            'Lihat',
                            [
                                // 'url' => '',
                                'title' => $model->nama_rs_puskesmas .' - level('. $model->hak_akses.')',
                                'value' => Url::to(['pengguna/detail','id'=>$model->id]),
                                'header' => 'Ubah Password',
                                'class' => 'modalButton btn btn-info btn-xs',
                                'style' => 'width:100%'
                            ]
                        );
                    },
                    'leadUpdate' => function ($url, $model) {
                        $url = Url::to(['pengguna/update', 'id' => $model->id]);
                        return Html::a('Ubah', $url, ['title' => 'update', 'class' => 'btn btn-success btn-xs', 'style' => 'width:100%']);
                    },
                    'leadDelete' => function ($url, $model) {
                        $url = Url::to(['pengguna/delete', 'id' => $model->id]);
                        return Html::a('Hapus', $url, [
                            'title'        => 'delete',
                            'data-confirm' => Yii::t('yii', 'Yakin mau hapus data ini?'),
                            'data-method'  => 'post',
                            'class' => 'btn btn-danger btn-xs',
                            'style' => 'width:100%'
                        ]);
                    },
                ]
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

<?php  //js code: 
    $this->registerJs(
    "$(document).on('ready pjax:success', function() {
            $('.modalButton').click(function(e){
            e.preventDefault(); //for prevent default behavior of <a> tag.
            $('#modal').modal('show');  
        });
        });
    ")
?>

<?php
yii\bootstrap\Modal::begin([
    'headerOptions' => [
        'id' => 'modalHeader'
    ],
    // 'header' => 'Ubah Profil',
    'id' => 'modal',
    'size' => 'modal-lg',
    // 'clientOptions' => ['backdrop' => 'static', 'keyboard' => true]
]);
echo "<div id='modalContent'></div>";
yii\bootstrap\Modal::end();
?>

views/pengguna/tambah.php
<?php

/*
* @Author 	: Dicky Ermawan S., S.T., MTA
* @Email 	: wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date 	: 2018-05-01 22:07:36
* @Last Modified by	 : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-12 21:30:36
*/

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Pengguna */

$this->title = 'Tambah Pengguna';
$this->params['breadcrumbs'][] = ['label' => 'Pengguna', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pengguna-create">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/pengguna/tes-bulk.php
<?php 
/*
* @Author 	: Dicky Ermawan S., S.T., MTA
* @Email 	: wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date 	: 2018-05-10 23:06:42
* @Last Modified by	 : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-12 21:30:26
*/

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
?>

<?=Html::beginForm(['controller/bulk'],'post');?>
<?=Html::dropDownList('action','',[''=>'Mark selected as: ','c'=>'Confirmed','nc'=>'No Confirmed'],['class'=>'dropdown',])?>
<?=Html::submitButton('Send', ['class' => 'btn btn-info',]);?>
<?=GridView::widget([
'dataProvider' => $dataProvider,
'columns' => [
['class' => 'yii\grid\CheckboxColumn'],
'id',
'nama_rs_puskesmas'
],
]); ?>
<?= Html::endForm();?> 

views/pengguna/update.php
<?php

/*
* @Author 	: Dicky Ermawan S., S.T., MTA
* @Email 	: wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date 	: 2018-05-01 22:07:36
* @Last Modified by	 : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-12 21:30:18
*/

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Pengguna */

$this->title = 'Update Pengguna';
$this->params['breadcrumbs'][] = ['label' => 'Pengguna', 'url' => ['index']];
// $this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pengguna-update">
	
	<div class="row" style="padding-bottom: 1.5%">
		<div class="col-md-12">
			<?= Html::a('Kembali', Yii::$app->request->referrer, ['class'=>'btn btn-info pull-right'])?>
		</div>
	</div>
    
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/pengguna/view.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-01 22:07:36
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-12 21:30:15
*/

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Pengguna */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Pengguna', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pengguna-view">

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'template'=>'<tr><th width="40%">{label}</th><td>{value}</td></tr>',
        'attributes' => [
            // 'id',
            'hak_akses',
            'username',
            // 'password',
            'nama_rs_puskesmas',
            'kontak',
            'email:email',
            'alamat:ntext',
        ],
    ]) ?>

</div>