controllers/PenggunaController.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-01 22:07:36
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-29 16:39:01
*/

namespace app\controllers;

use Yii;
use app\models\Pengguna;
use app\models\PenggunaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\form\ActiveForm;


use yii\filters\AccessControl;
use app\components\AccessRule;
use app\models\User;

/**
 * PenggunaController implements the CRUD actions for Pengguna model.
 */
class PenggunaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // We will override the default rule config with the new AccessRule class
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'only' => [
                    //super_admin
                    'index', 'tambah', 'detail', 'delete'
                ],
                'rules' => [
                    [
                        'actions' => ['index', 'tambah', 'detail', 'delete'],
                        'allow' => true,
                        'roles' => [
                            User::ROLE_SUPERADMIN,
                        ],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pengguna models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PenggunaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTesBulk()
    {
        $searchModel = new PenggunaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;

        return $this->render('tes-bulk', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pengguna model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pengguna model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionValidasi()
    {
        $model = new Pengguna();
        // $model->scenario = 'update';

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()))
        {
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
            // return 'kakek';

            // return $model->scenario;
        }
    }

    public function actionTambah()
    {
        $model = new Pengguna();
        $model->scenario = 'tambah';

        // print_r($model->scenario);exit;

        // if ($model->load(Yii::$app->request->post()) && $model->save()) {
        if ($model->load(Yii::$app->request->post())) {
            // $model->password = password_hash($model->password, PASSWORD_DEFAULT);
            if($model->save()) {
                Yii::$app->getSession()->setFlash('success', 'Pengguna Berhasil ditambah.');
                return $this->redirect('index');
            }
        }
        $model->hak_akses = 'user';
        return $this->render('tambah', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pengguna model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        // $model->scenario = 'update';

        if ($model->load(Yii::$app->request->post())) {
            // $model->password = password_hash($model->password, PASSWORD_DEFAULT);
            if($model->save()) {
                Yii::$app->getSession()->setFlash('success', 'Pengguna Berhasil diubah.');
                return $this->redirect('index');
                // return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pengguna model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pengguna model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pengguna the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pengguna::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    // =============================================UNTUK MODAL====================================================
    public function actionDetail()
    {
        $model = $this->findModel($_GET['id']);

        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            $model->refresh();
        } else {
            return $this->renderAjax('view',[
                'model' => $model
            ]);
        }
    }
}

controllers/RujukanController.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-11 17:37:35
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-07-06 10:20:48
*/

namespace app\controllers;

use Yii;
use yii\helpers\Url;
use app\models\Pengguna;
use app\models\Rujukan;
use app\models\RujukanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;

use yii\filters\AccessControl;
use app\components\AccessRule;
use app\models\User;


use ElephantIO\Client as Socket;
use ElephantIO\Engine\SocketIO\Version1X;

/**
 * RujukanController implements the CRUD actions for Rujukan model.
 */
class RujukanController extends Controller
{

    protected $socket;
    protected $pageSize;

    /**
     * Inisialisasi awal sebelum method dieksekusi.
     * @return void
     */
    public function init()
    {
        $this->socket = new Socket(new Version1X('127.0.0.1:3000'));
        $this->pageSize = 15;
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // We will override the default rule config with the new AccessRule class
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'only' => [
                    //admin
                    'monitoring', 'monitoring-partial','proses',

                    //user
                    'tambah','riwayat', 'riwayat-partial','cetak', 'cetak-tes'
                ],
                'rules' => [
                    [
                        'actions' => ['monitoring', 'proses', 'monitoring-partial'],
                        'allow' => true,
                        'roles' => [
                            User::ROLE_ADMIN,
                        ],
                    ],
                    [
                        'actions' => ['tambah', 'riwayat', 'riwayat-partial', 'cetak', 'cetak-tes'],
                        'allow' => true,
                        'roles' => [
                            User::ROLE_USER,
                        ],
                    ],
                ],
            ],

            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'cetak' => ['POST'],
                ],
            ],
        ];
    }

    
    /**
     * Displays a single Rujukan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing Rujukan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    /**
     * Finds the Rujukan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Rujukan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rujukan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    //================================================USER
    public function actionHapus($id)
    {
        $this->findModel($id)->delete();
        //untuk socket
        $this->socket->initialize();
        $this->socket->emit('hapus_rujukan', []);
        $this->socket->close();
        return $this->redirect(['riwayat']);
    }

    public function actionRiwayatPartial()
    {
        $searchModel = new RujukanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, Yii::$app->user->identity->id);
        $dataProvider->pagination->pageSize=10;

        return $this->renderPartial('riwayat-partial', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }
    public function actionRiwayat()
    {
        $searchModel = new RujukanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, Yii::$app->user->identity->id);
        $dataProvider->pagination->pageSize = 10;

        return $this->render('riwayat', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTambah()
    {
        $model = new Rujukan();

        if ($model->load(Yii::$app->request->post())) {
            date_default_timezone_set("Asia/Jakarta");
            $model->tgl_masuk = date('Y-m-d  H:i:s');
            $model->jam_masuk = date('H:i:s');

            $model->status = Rujukan::MENUNGGU;
// exit;
            if($model->save()){
                Yii::$app->getSession()->setFlash('success', 'Data Rujukan berhasil dikirimkan, harap menunggu respon.');

                //untuk socket
                $this->socket->initialize();
                $this->socket->emit('tambah_rujukan', []);
                $this->socket->close();

                // return 'sukses save';
// exit;
                //NANTI DIAKTIFKAN LAGI, ini utk ngetes biar form terisi terus
                return $this->redirect(['rujukan/riwayat']);
            }else{
                echo 'GAGAL save';
            
            // else{ //UNTUK DEBUG, ELSE dari BERHASIL SAVE
                print_r($model);
            }
            // }
        }

        $model->asal_rujukan = Yii::$app->user->identity->id;
        $model->tujuan_rujukan = 2;

        $model->jenis = 'Ibu';
        // $model->jk = 'Perempuan';

        $model->tujuan_r = Pengguna::findOne($model->tujuan_rujukan)->nama_rs_puskesmas;
        $model->asal_r = Yii::$app->user->identity->nama_rs_puskesmas;

        return $this->render('tambah', [
            'model' => $model,
        ]);
    }

    public function actionUpdateJk()
    {
        return $this->renderPartial('update-jk',[
            'id' => $_POST['id']
        ]);
    }

    public function actionUpdateUmur()
    {
        return $this->renderPartial('update-umur',[
            'id' => $_POST['id']
        ]);
    }

    public function actionUpdateCaraBayar()
    {
        return $this->renderPartial('update-cara-bayar',[
            'id' => $_POST['id']
        ]);
    }



    //UNTUK CETAK HASIL RUJUKAN

    public function actionCetakTes()
    {
        $model = Rujukan::findOne(2);
// echo 'asd';
        // exit;

        return $this->render('_user-cetak-rujukan',['model'=>$model]);
    }

    public function actionCetak($id)
    {
        $model = $this->findModel($id);

        $content = $this->renderPartial('_user-cetak-rujukan',['model'=>$model]);

        date_default_timezone_set('Asia/Jakarta');
        $tanggal = Yii::$app->formatter->asDate(date('d M y'));
        $jam = date('H:i:s');
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            'format' => Pdf::FORMAT_LEGAL, 
            'orientation' => Pdf::ORIENT_PORTRAIT, 
            // 'destination' => Pdf::DEST_BROWSER, 
            'destination' => Pdf::DEST_DOWNLOAD, 
            'content' => $content,  
            'filename' => 'Bukti Rujukan a.n '.$model->nama.' - '. $tanggal .'.pdf',
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            'cssInline' => '.table > thead > tr > th,.table > tbody > tr > th,.table > tfoot > tr > th,.table > thead > tr > td,.table > tbody > tr > td,.table > tfoot > tr > td { padding: 3px; line-height: 1.42857143; vertical-align: top; border-top: 1px solid #dddddd;}',
            'methods' => [ 
                'SetHeader' => ['Dicetak Otomatis Oleh: SIMPONI||Pada: ' . $tanggal .', '. $jam],
                'SetFooter'=>['Hal. {PAGENO}'],
            ]

        ]);
        
        return $pdf->render(); 
    }





    // <==========================Akun RS==============================================================>
    public function actionUnreadCounter()
    {
        return Rujukan::find()->where(['status' => 'Menunggu'])->count();
    }
    public function actionMonitoring()
    {
        $searchModel = new RujukanSearch();
        $dataProvider = $searchModel->searchMonitoring(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;

        // print_r($dataProvider->getPagination());exit;

        return $this->render('rs-monitoring', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    //untuk render partial socket
    public function actionMonitoringPartial()
    {
        $searchModel = new RujukanSearch();
        $dataProvider = $searchModel->searchMonitoring(Yii::$app->request->queryParams);

        $dataProvider->pagination->pageSize=10;
        // $pagination = $dataProvider->getPagination();
        // $pagination->route = 'rujukan/monitoring';
        // $dataProvider->pagination->route = 'rujukan/monitoring';

        // print_r($dataProvider->getPagination());exit;

        return $this->renderPartial('rs-monitoring-partial', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    //untuk notif di navbar

views/rujukan/_search.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-11 17:37:35
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-11 17:39:24
*/

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RujukanSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rujukan-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'tgl_masuk') ?>

    <?= $form->field($model, 'jenis') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'jk') ?>

    <?php // echo $form->field($model, 'tplahir') ?>

    <?php // echo $form->field($model, 'tglahir') ?>

    <?php // echo $form->field($model, 'umur') ?>

    <?php // echo $form->field($model, 'alamat') ?>

    <?php // echo $form->field($model, 'cara_bayar') ?>

    <?php // echo $form->field($model, 'nik') ?>

    <?php // echo $form->field($model, 'no_bpjs_jkd') ?>

    <?php // echo $form->field($model, 'asal_rujukan') ?>

    <?php // echo $form->field($model, 'tujuan_rujukan') ?>

    <?php // echo $form->field($model, 'alasan_rujukan') ?>

    <?php // echo $form->field($model, 'anamnesa') ?>

    <?php // echo $form->field($model, 'kesadaran') ?>

    <?php // echo $form->field($model, 'tekanan_darah') ?>

    <?php // echo $form->field($model, 'nadi') ?>

    <?php // echo $form->field($model, 'suhu') ?>

    <?php // echo $form->field($model, 'pernapasan') ?>

    <?php // echo $form->field($model, 'nyeri') ?>

    <?php // echo $form->field($model, 'pemeriksaan_fisik') ?>

    <?php // echo $form->field($model, 'pemeriksaan_penunjang') ?>

    <?php // echo $form->field($model, 'diagnosa') ?>

    <?php // echo $form->field($model, 'tindakan_yg_sdh_diberikan') ?>

    <?php // echo $form->field($model, 'info_balik') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rujukan/riwayat-partial.php
<?php

/*
* @Author 	: Dicky Ermawan S., S.T., MTA
* @Email 	: wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date 	: 2018-05-27 05:01:17
* @Last Modified by	 : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-07-06 09:29:33
*/


use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use app\components\Penolong;
use yii\widgets\Pjax;

?>

<div class="table-responsive tabel-riwayat-rujukan">
<?php Pjax::begin(); ?>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'pager' => [
        'firstPageLabel' => 'Pertama',
        'lastPageLabel'  => 'Terakhir'
    ],
    'rowOptions' => function($model) {
        if ($model->status==='Menunggu') return ['class' => 'warning'];
    },
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        // 'id',
        [
            'attribute' => 'tgl_masuk',
            'headerOptions' => ['style' => 'width:14%'],
            'value' => function($model){
                return $model->tgl_masuk;
                // return Yii::$app->formatter->asDate($model->tgl_masuk);
            },
            'filterInputOptions' => [
                'class'       => 'form-control',
                'placeholder' => 'Contoh: 2018-12-23'
             ]
        ],
        'jam_masuk',
        'nama',
        [
            'attribute' => 'asal_rujukan_text',
            'header' => '<font color="#2fa4e">Asal Rujukan</font>',
            'value' => function ($model) {
                return $model->asal_rujukan_text;
            },
            'format' => 'html',
        ],
        [
            'attribute' => 'tujuan_rujukan_text',
            'header' => '<font color="#2fa4e">Tujuan Rujukan</font>',
            'value' => function ($model) {
                return $model->tujuan_rujukan_text;
            },
            'format' => 'html',
        ],
        'alasan_rujukan:ntext',
        'diagnosa:ntext',
        'info_balik:ntext',
        [
            'headerOptions' => ['class' => 'text-center'],
            'contentOptions' => ['class' => 'text-center'],
            'attribute' => 'status',
            'value' => function ($model) {
                return Penolong::label($model->status);
            },
            'format' => 'html',
        ],

        [
            'class'    => 'yii\grid\ActionColumn',
            'header' => 'Aksi',
            'headerOptions' => ['style' => 'color:#2fa4e7; text-align:center;'],
            'contentOptions' => ['class' => 'text-center'],
            'template' => '{lihat}',
            'visibleButtons'=>[
                'lihat'=> function($model){
                      return $model->status==='Diterima' || $model->status==='Tidak Diterima';
                 },
            ],
            'buttons'  => [                    
                'lihat' => function ($url, $model) {
                    $url = Url::to(['rujukan/cetak', 'id' => $model->id]);
                    return Html::a('<span class="">Print</span>', $url, [
                        'class' => 'btn btn-info btn-xs',
                        'style' => 'width:100%',
                        // 'target' => '_blank',
                        // 'data-toggle'=>'tooltip', 
                        'title'=>'Akan Mencetak PDF di Tab Baru.',
                        'data' => [
                            'method' => 'post',
                        ],
                    ]);
                },
            ]
        ],        
    ],
]); ?>
<?php Pjax::end(); ?>
</div>

views/rujukan/riwayat.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-11 17:37:35
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-07-06 09:29:28
*/

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use app\components\Penolong;
use yii\widgets\Pjax;
use kartik\icons\Icon;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RujukanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Riwayat Rujukan';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rujukan-index">

    <p>
        <?= Html::a(Icon::show('ambulance').' &nbsp;Tambah Rujukan', ['tambah'], ['class' => 'btn btn-success']) ?>
    </p>

    <div class="table-responsive tabel-riwayat-rujukan">
    <?php Pjax::begin([
        'id' => 'pjax-tb-riw',
        ]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'pager' => [
            'firstPageLabel' => 'Pertama',
            'lastPageLabel'  => 'Terakhir'
        ],
        'rowOptions' => function($model) {
            if ($model->status==='Menunggu') return ['class' => 'warning'];
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            [
                'attribute' => 'tgl_masuk',
                'headerOptions' => ['style' => 'width:14%'],
                'value' => function($model){
                    return $model->tgl_masuk;
                    // return Yii::$app->formatter->asDate($model->tgl_masuk);
                },
                'filterInputOptions' => [
                    'class'       => 'form-control',
                    'placeholder' => 'Contoh: 2018-12-23'
                 ]
            ],
            'jam_masuk',
            'nama',
            [
                'attribute' => 'asal_rujukan_text',
                'header' => '<font color="#2fa4e">Asal Rujukan</font>',
                'value' => function ($model) {
                    return $model->asal_rujukan_text;
                },
                'format' => 'html',
            ],
            [
                'attribute' => 'tujuan_rujukan_text',
                'header' => '<font color="#2fa4e">Tujuan Rujukan</font>',
                'value' => function ($model) {
                    return $model->tujuan_rujukan_text;
                },
                'format' => 'html',
            ],
            'alasan_rujukan:ntext',
            'diagnosa:ntext',
            'info_balik:ntext',
            // [
            //     'headerOptions' => ['class' => 'text-center'],
            //     'contentOptions' => ['class' => 'text-center'],
            //     'attribute' => 'status',
            //     'value' => function ($model) {
            //         return Penolong::label($model->status);
            //     },
            //     'format' => 'html',
            // ],
            [
                'class'    => 'yii\grid\ActionColumn',
                'header' => 'Status',
                'headerOptions' => ['style' => 'color:#2fa4e7; text-align:center;'],
                'contentOptions' => ['class' => 'text-center'],
                'template' => '{status}{hapus}',
                'visibleButtons'=>[
                    'hapus'=> function($model){
                          return $model->status==='Menunggu';
                     },
                ],
                'buttons'  => [     
                    'status' => function ($url, $model) {
                        return Penolong::label($model->status);
                    },               
                    'hapus' => function ($url, $model) {
                        $url = Url::to(['rujukan/hapus', 'id' => $model->id]);
                        return Html::a('<span class=""><li class="fa fa-trash"></li></span>', $url, [
                            'class' => 'btn btn-danger btn-xs',
                            'style' => 'margin-left: 5px;margin-bottom: 1px;',
                            'data-toggle'=>'tooltip', 
                            'title'=>'Hapus Rujukan',
                            'data' => [
                                'method' => 'post',
                            ],
                        ]);
                    },
                ]
            ],

            [
                'class'    => 'yii\grid\ActionColumn',
                'header' => 'Aksi',
                'headerOptions' => ['style' => 'color:#2fa4e7; text-align:center;'],
                'contentOptions' => ['class' => 'text-center'],
                'template' => '{cetak}',
                'visibleButtons'=>[
                    'cetak'=> function($model){
                          return $model->status==='Diterima' || $model->status==='Tidak Diterima';
                     },
                ],
                'buttons'  => [                    
                    'cetak' => function ($url, $model) {
                        $url = Url::to(['rujukan/cetak', 'id' => $model->id]);
                        return Html::a('<span class="">Print</span>', $url, [
                            'class' => 'btn btn-info btn-xs',
                            'style' => 'width:100%',
                            // 'target' => '_blank',
                            // 'data-toggle'=>'tooltip', 
                            'title'=>'Akan Mencetak PDF di Tab Baru.',
                            'data' => [
                                'method' => 'post',
                            ],
                        ]);
                    },
                ]
            ],


            // 'jenis',
            // 'jk',
            //'tplahir',
            //'tglahir',
            //'umur',
            //'alamat:ntext',
            //'cara_bayar',
            //'nik',
            //'no_bpjs_jkd',
            //'anamnesa:ntext',
            //'kesadaran',
            //'tekanan_darah',
            //'nadi',
            //'suhu',
            //'pernapasan',
            //'nyeri',
            //'pemeriksaan_fisik:ntext',
            //'pemeriksaan_penunjang:ntext',
            //'tindakan_yg_sdh_diberikan:ntext',
            //'status',

            // ['class' => 'yii\grid\ActionColumn'],

            
        ],
    ]); ?>
    <?php Pjax::end(); ?>
    </div>
    
</div>

views/rujukan/tambah.php
<?php

/*
* @Author 	: Dicky Ermawan S., S.T., MTA
* @Email 	: wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date 	: 2018-05-11 17:37:35
* @Last Modified by	 : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-05-11 18:03:52
*/

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Rujukan */

$this->title = 'Tambah Rujukan';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rujukan-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>