controllers/PesanController.php
<?php

/*
* @Author   : Dicky Ermawan S., S.T., MTA
* @Email    : wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date     : 2018-05-31 13:10:23
* @Last Modified by  : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-06-27 10:36:37
*/


namespace app\controllers;

use Yii;
use yii\base\view;
use yii\filters\AccessControl;
use app\components\AccessRule;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\User;
use app\models\Pengguna;
use app\models\Chat;

use ElephantIO\Client as Socket;
use ElephantIO\Engine\SocketIO\Version1X;

class PesanController extends Controller
{   


    protected $socket;

    public function init()
    {
        $this->socket = new Socket(new Version1X('127.0.0.1:3000'));
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // We will override the default rule config with the new AccessRule class
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'only' => [
                    //admin, user
                    'index', 'chat', 'kirim'
                ],
                'rules' => [
                    [
                        'actions' => ['index', 'chat', 'kirim'],
                        'allow' => true,
                        'roles' => [
                            User::ROLE_ADMIN,
                            User::ROLE_USER,
                        ],
                    ],
                ],
            ],
        ];
    }

    public function actionChat()
    {   
        if(Yii::$app->user->identity->hak_akses==User::ROLE_ADMIN){
            $this->redirect(['pesan/index']);
        }else
        {
            $this->redirect(['pesan/index?id=2']);
        }
    }



	public function actionIndex()
	{	

        if(isset($_GET['id'])){
            Chat::updateAll([
                'baca' => 1,
            ],
            [
                'dari' => $_GET['id'],
                'untuk' => Yii::$app->user->identity->id
            ]);
        }

        if(Yii::$app->user->identity->hak_akses==User::ROLE_ADMIN){
            $kontak = Pengguna::find()
                ->where(['!=', 'hak_akses', 'super_admin'])
                ->andWhere(['!=', 'hak_akses', 'admin'])
                ->orderBy('nama_rs_puskesmas', SORT_ASC)
                ->all();
        }else
        {
            $kontak = Pengguna::find()
                ->where(['!=', 'hak_akses', 'super_admin'])
                ->andWhere(['!=', 'hak_akses', 'user'])
                ->orderBy('nama_rs_puskesmas', SORT_ASC)
                ->all();
        }

		return $this->render('index',[
			
            'kontak' => $kontak,

		]);
	}

    public function actionKirim()
    {
        date_default_timezone_set('Asia/Jakarta');

        $model = new Chat;
        $model->waktu = date('Y-m-d H:i:s', time());
        $model->dari = $_POST['dari'];
        $model->untuk = $_POST['untuk'];
        $model->isi = $_POST['isi'];
        $model->baca = 0;
        $model->save();

        
        // if($model->save)
        // {
            $this->socket->initialize();
            $this->socket->emit('chat_kirim', []);
            $this->socket->close();
        // }

        return true;
    }

    //untuk update status baca
    public function actionBaca()
    {
        Chat::updateAll([
            'baca' => 1,
        ],
        [
            'dari' => $_POST['dari'],
            'untuk' => Yii::$app->user->identity->id
        ]);

        //untuk socket
        $this->socket->initialize();
        $this->socket->emit('chat_baca', []);
        $this->socket->close();

        $respon = $_POST['dari'];
        

        return $respon;
    }

}

views/pesan/index.php
<?php

/*
* @Author 	: Dicky Ermawan S., S.T., MTA
* @Email 	: wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date 	: 2018-05-31 13:16:31
* @Last Modified by	 : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-06-26 21:11:13
*/

use Yii;
use yii\helpers\Url;
use yii\widgets\Pjax;
use app\components\Penolong;

use app\models\Chat;
use app\models\ChatSearch;

use app\assets\ChatAsset;
ChatAsset::register($this);

$this->title = 'Pesan';

?>

<div class="row">
	
	<div class="col-md-12">
		
		

		<!-- view kontak -->
		<div class="col-md-4" style="background-color: white">

			<div class="nav-chat list-group" id="chat-group">
				<?php
				$unreadKontak = Yii::$app->getDb()->createCommand('SELECT dari, count(*) as unread from chat where dari != 2 and baca =0 group by dari')->queryAll();
				$unreadKontakA = array_map(function($v){
					return $v['dari'];
				}, $unreadKontak);
				$unreadKontakB = array_map(function($v){
					return $v['unread'];
				}, $unreadKontak);
				$unreadKontak = array_combine($unreadKontakA, $unreadKontakB);

				// print_r($unreadKontak);
					// $aktif = 'active';
					foreach($kontak as $k=>$key)
					{
						// if($k!=0){
						// 	$aktif = '';
						// }
						echo '
							<a id="chat-kontak" href="?id='.$kontak[$k]->id.'" class="list-group-item '.Penolong::activeChat($kontak[$k]->id, $_GET['id']).'">
							'.Penolong::unreadKontak($unreadKontak, $kontak[$k]->id).'
								<h5 class="list-group-item-heading"> <li class="fa fa-user"></li> <strong><em>'.$kontak[$k]->nama_rs_puskesmas.'</em></strong></h5>
								 
							  </a>
						';
						
					}
					
				?>
			</div>

		</div>
	
		<!-- view chat -->
		<div class="col-md-8" style="background-color: white">
			
			<!-- <?= $_GET['id'] ?> -->

			<!-- <br><br> -->

			<div class="container">
			<div class="row">
		        <div class="col-md-8">
		            <div class="panel panel-primary">
		                <div class="panel-heading">
		                    <span class="glyphicon glyphicon-comment"></span> <?=Chat::profilKontak($_GET['id'], 'nama_rs_puskesmas')?>
		                </div>

		                

		                <div class="panel-body" id="kotak-chat">
		                	<?php Pjax::begin([
								'id' => 'pjax-chat',
								'timeout' => 5000
							]); ?>
		                    <ul class="chat">
		                    	<!-- untuk ambil chat -->
								<?php 
									$chat = Chat::kotakChat(Yii::$app->user->identity->id, $_GET['id']);

									foreach ($chat as $c)
									{
										if($c->dari==Yii::$app->user->identity->id)
										{
											echo ' <li class="right clearfix"><span class="chat-img pull-right">
						                            <img src="'.Yii::getAlias('@web').'/img/user.jpg" alt="User Avatar" class="img-circle" width="45px"/>
						                        </span>
					                            <div class="chat-body clearfix">
					                                <div class="header">
					                                    <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>'.$c->waktu.'</small>
					                                    <strong class="pull-right primary-font">'.$c->dari_text.'</strong>
					                                </div>
					                                <p>
					                                    '.$c->isi.'
					                                </p>
					                            </div>
					                        </li>';
										}else
										{
											echo '
												<li class="left clearfix"><span class="chat-img pull-left">
						                            <img src="'.Yii::getAlias('@web').'/img/user-you.jpg" alt="User Avatar" class="img-circle" width="45px"/>
						                        </span>
						                            <div class="chat-body clearfix">
						                                <div class="header">
						                                    <strong class="primary-font">'.$c->dari_text.'</strong> <small class="pull-right text-muted">
						                                        <span class="glyphicon glyphicon-time"></span>'.$c->waktu.'</small>
						                                </div>
						                                <p>
						                                    '.$c->isi.'
						                                </p>
						                            </div>
						                        </li>
											';
										}
										
									}

								?>

		                    </ul>
		                    <?php Pjax::end(); ?>
		                </div>
						

						

		                <div class="panel-footer">
		                    <div class="input-group">
		                    	<input type="hidden" value="<?= Yii::$app->user->identity->id ?>" id="dari">
		                    	<input type="hidden" value="<?= $_GET['id'] ?>" id="untuk">
		                        <input id="isi-chat" type="text" class="form-control input-sm" placeholder="Ketik pesan anda disini..." />
		                        <span class="input-group-btn">
		                            <button class="btn btn-warning btn-sm" id="btn-chat">
		                                Send</button>
		                        </span>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>
		</div>

		</div>


	</div>

</div>

<?php

$this->registerJs($this->render('index.js'));

views/pesan/notif.php
<?php

/*
* @Author 	: Dicky Ermawan S., S.T., MTA
* @Email 	: wanasaja@gmail.com
* @Dashboard: http://dickyermawan.dev.php.or.id/
* @Date 	: 2018-06-18 19:54:35
* @Last Modified by	 : Dicky Ermawan S., S.T., MTA
* @Last Modified time: 2018-06-18 20:53:14
*/

use yii\helpers\Url;

if($unreadPesan){
	$unreadPesan = '<a class="unread-pesan" href="'.Url::base().'/pesan/chat">Pesan <span class="badge blink_text" style="margin-left: 8px;">'.$unreadPesan.'</span></a>';
	$unreadPesan .= '<audio autoplay><source src="'.Url::base().'/notif/pesan.ogg"></audio>';
}else{
	$unreadPesan = '<a class="unread-pesan" href="'.Url::base().'/pesan/chat">Pesan</a>';
}

echo $unreadPesan;